### ISSUE TITLE
Bottomless compost bucket support

### ISSUE THREAD

**Issue by TicTac7x** [PidgeBirb/compost-helper#1]
This is not exactly an issue, but wanted to leave this here that "Bottomless compost bucket" is already fully supported by the plugin "Item Charges Improved" created by me. Currently it shows the number of compost and type in infobox. New version that im working on will also show tooltip when hovering in inventory.

![image](https://github.com/PidgeBirb/compost-helper/assets/75637554/63b3de6b-4aae-42fd-b1c0-ce2d834c6c0b)

**Comment by PidgeBirb** [comment]
Ah, missed that. Cool that you added that! Thanks for letting me know, I'll remove it from my todo list.
