### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by TicTac7x** [PidgeBirb/compost-helper#2]
Plugin is throwing null pointer exceptions to the console, noticed this while developing my own plugins while having your plugin enabled.

![image](https://github.com/PidgeBirb/compost-helper/assets/75637554/61226637-78c4-4d9f-aeeb-b14edd25b40f)

Checked your code out, variable `visibleCompostBin` is `null`, I recommend using `@Nullable` or `Optional<CompostBin>`.

**Comment by PidgeBirb** [comment]
Fixed, thanks for letting me know!
